# Generated by Django 4.0 on 2021-12-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='ash.png', upload_to=''),
        ),
    ]
