# Generated by Django 4.0 on 2021-12-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
