# Generated by Django 4.0 on 2021-12-16 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_randomuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomUser',
        ),
    ]
