# Generated by Django 4.0 on 2021-12-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_delete_randomuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rival',
            field=models.TextField(default=1),
        ),
    ]
