# Generated by Django 4.0 on 2021-12-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_post_rival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rival',
            field=models.TextField(default='John'),
        ),
    ]
