# Generated by Django 4.0 on 2021-12-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_alter_post_rival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rival',
            field=models.CharField(default='Liderman', max_length=100),
        ),
    ]
