# Generated by Django 4.0 on 2021-12-16 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0009_alter_post_rival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rival',
        ),
    ]
