# Generated by Django 4.0 on 2021-12-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0013_post_rival'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resultado',
            field=models.CharField(default='Derrota!', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='rival',
            field=models.CharField(default='Paulina', max_length=100),
        ),
    ]
